name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

env:
  LC_ALL: C.UTF-8
  LANG: C.UTF-8

jobs:
  test-and-lint:
    name: Lint, Format Check & Tests (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          # Ensure CI has extras required by tests (crypto, asyncio test helpers, etc.)
          pip install pycryptodome pytest-asyncio ruff black pytest

      - name: Lint with ruff
        run: |
          echo "Running ruff..."
          ruff check .

      - name: Check formatting with black
        run: |
          echo "Checking formatting with black..."
          black --check .

      - name: Run tests (with retries and strict options)
        run: |
          set -euo pipefail
          echo "Running pytest with retries..."
          # Retry pytest up to 3 times to mitigate flaky network/timing issues on CI
          for i in 1 2 3; do
            pytest -q --disable-warnings --maxfail=1 && break
            echo "Pytest attempt $i failed, retrying..." >&2
            sleep $((i * 5))
            if [ "$i" = "3" ]; then
              echo "Pytest failed after 3 attempts" >&2
              exit 1
            fi
          done
